import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const u=await getChatGPTUser();if(!u)return json({error:'교사 로그인이 필요해요.'},401);try{await env.DB!.prepare('CREATE TABLE IF NOT EXISTS book_metadata (id TEXT PRIMARY KEY, owner TEXT NOT NULL, author TEXT, publisher TEXT)').run();const r=await env.DB!.prepare('SELECT r.*, m.author, m.publisher FROM recommendations r LEFT JOIN book_metadata m ON r.id=m.id AND r.owner=m.owner WHERE r.owner = ? ORDER BY r.created DESC').bind(u.userId).all();return json({records:r.results});}catch(e){console.error('records load',e);return json({error:'책장을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.'},503)}}
export async function POST(req:Request){const u=await getChatGPTUser();if(!u)return json({error:'교사 로그인이 필요해요.'},401);try{await env.DB!.prepare('CREATE TABLE IF NOT EXISTS book_metadata (id TEXT PRIMARY KEY, owner TEXT NOT NULL, author TEXT, publisher TEXT)').run();const b=await req.json() as Record<string,unknown>;const str=(k:string,max:number)=>typeof b[k]==='string'?(b[k] as string).trim().slice(0,max):'';const name=str('name',50),title=str('title',200),reason=str('reason',3000),id=str('id',50),photo=str('photo',200),audio=str('audio',200);if(!name||!title||!id||(!reason&&!audio))return json({error:'이름, 책 제목, 추천 이유를 확인해 주세요.'},400);for(const key of [photo,audio])if(key&&!key.startsWith(u.userId+'/'))return json({error:'사진 또는 음성을 다시 등록해 주세요.'},400);const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=(k:string)=>parts.find(p=>p.type===k)?.value;const today=`${get('year')}-${get('month')}-${get('day')}`;const selectedDate=b.date===undefined?today:b.date;if(typeof selectedDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(selectedDate)||selectedDate.startsWith('0000')||!Number.isFinite(Date.parse(selectedDate+'T00:00:00Z'))||new Date(selectedDate+'T00:00:00Z').toISOString().slice(0,10)!==selectedDate)return json({error:'올바른 추천 날짜를 선택해 주세요.'},400);const link=str('link',1500);if(link&&!/^https:\/\/(www\.)?yes24\.com\//.test(link))return json({error:'책 판매처 링크를 확인해 주세요.'},400);if(req.method==='PUT'){const result=await env.DB!.prepare('UPDATE recommendations SET name=?,title=?,reason=?,date=?,photo=?,audio=?,cover=?,link=?,provider=? WHERE id=? AND owner=?').bind(name,title,reason,selectedDate,photo||null,audio||null,str('cover',1500)||null,link||null,link?'예스24':null,id,u.userId).run();if(!result.meta.changes)return json({error:'수정할 기록을 찾을 수 없어요.'},404);await env.DB!.prepare('INSERT INTO book_metadata (id,owner,author,publisher) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET author=excluded.author,publisher=excluded.publisher WHERE book_metadata.owner=excluded.owner').bind(id,u.userId,str('author',200),str('publisher',200)).run();return json({ok:true});}await env.DB!.prepare('INSERT INTO recommendations (id,owner,name,title,reason,date,photo,audio,cover,link,provider,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,u.userId,name,title,reason,selectedDate,photo||null,audio||null,str('cover',1500)||null,link||null,link?'예스24':null,new Date().toISOString()).run();await env.DB!.prepare('INSERT INTO book_metadata (id,owner,author,publisher) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET author=excluded.author,publisher=excluded.publisher WHERE book_metadata.owner=excluded.owner').bind(id,u.userId,str('author',200),str('publisher',200)).run();return json({ok:true});}catch(e){console.error('record save',e);return json({error:'저장하지 못했어요. 입력 내용은 그대로 있으니 다시 시도해 주세요.'},503)}}



export async function PUT(req:Request){return POST(req)}
export async function DELETE(req:Request){const u=await getChatGPTUser();if(!u)return json({error:'교사 로그인이 필요해요.'},401);try{const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'삭제할 기록을 선택해 주세요.'},400);const result=await env.DB!.prepare('DELETE FROM recommendations WHERE id=? AND owner=?').bind(id,u.userId).run();if(!result.meta.changes)return json({error:'삭제할 기록을 찾을 수 없어요.'},404);return json({ok:true});}catch{return json({error:'삭제하지 못했어요. 다시 시도해 주세요.'},503)}}
